### ISSUE TITLE
Unable to start on MacOS

### ISSUE THREAD

**Issue by onimsha** [ngoduykhanh/wireguard-ui#11]
We should make the docker-compose.yaml compatible with such OS like MacOS. Currently it's using local folder mounts which may not available everywhere, especially macOS.  Once start it will threw complaints like this 

```
Creating wgui ... error

ERROR: for wgui  Cannot start service wg: Mounts denied:
The path /etc/wireguard
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.

ERROR: for wg  Cannot start service wg: Mounts denied:
The path /etc/wireguard
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERROR: Encountered errors while bringing up the project.
```

Better to declare a local volume to get rid of this kind of error.

**Comment by ngoduykhanh** [comment]
The main purpose of that local folder mount is to write config to Wireguard instance which running on the host. Then, Wireguard daemon will be reloaded as described [here](https://github.com/ngoduykhanh/wireguard-ui#auto-restart-wireguard-daemon).

Since it is just an example, you can always modify it to fit your actual setup :)
