### ISSUE TITLE
Change password after initialization

### ISSUE THREAD

**Issue by denny0754** [ngoduykhanh/wireguard-ui#282]
Hello,

I've installed the binary on my linux virtual machine and the pair user/password is the default one: admin/admin.

I'm wondering how to change the password of user "admin".
I'm not seeing any access settings from the UI and neither running the help page of the binary gives any insight.

Though I see that in file `db/server/users.json` there is an hashed password and a password, the latter being empty.
I tried to change the "password" item but if I try to enter it, after a restart of the service, into the UI it gives me an "invalid credentials" error.

Thanks.

**Comment by Raniz85** [comment]
You can use the HashPassword function from the source in the Go playground to hash a new password.

Here's a playground you can modify with your own password

https://play.golang.com/p/DXf3lgIBzLp

**Comment by ByteDream** [comment]
The functionality to update the password afterwards was introduced in #280. But since this got merged, no new binary release were published so you have to build the binary yourself to get this changes. Instructions to do so are documented in the [README](https://github.com/ngoduykhanh/wireguard-ui#build-binary-file) (or you could use the docker image, the changes are already active there).
