### ISSUE TITLE
Cannot import configs to Wireguard client

### ISSUE THREAD

**Issue by bsnsp** [ngoduykhanh/wireguard-ui#307]
I cannot import config files that I have downloaded from wireguard ui to Wireguard client.

I get an error when importing the configuration:

Unable to import the configuration: 
Invalid Entry in [Interface] section: fwmark

**Comment by andycandy-de** [comment]
I also had this issue. It's because the fwmark is defined in the client configuration file. Just delete this entry. But I don't really understand why it is in the client configuration. My understanding was that the fwmark is a serverside thing. But this setting is not present in the server `wg0.conf` file. This should be improved.

**Comment by Festival0103** [comment]
@bsnsp @andycandy-de 
Maybe you already solved this, but in case someone else will search for this.
Just delete entry from line "Forward Mark" in the General Settings of Wireguard UI.
![Screenshot 2023-02-17 223030](https://user-images.githubusercontent.com/112980055/219724876-5c4cfea3-5894-430b-87e4-99ba481ea2d5.png)
And then apply config on the top right.

**Comment by systemcrash** [comment]
This is known, and fixed in #279
