### ISSUE TITLE
Installing on Alpine Linux (not in container)

### ISSUE THREAD

**Issue by mlanner** [ngoduykhanh/wireguard-ui#318]
I tried to install the amd64 binary on Alpine Linux, but when I try to execute it with `./wireguard-ui`, I just get:

```
./wireguard-ui: cannot execute: required file not found
```

I'm assuming I'm missing some dependency? If so, what is it? I tried scouring the Dockerfile and the Docker compose file, as those refer to Alpine, but so far I've not found anything that got me any further.

I'd be happy to write up documentation for the project for how to run it on Alpine (in a VM) once I get this working.

Thanks!

**Comment by ByteDream** [comment]
It seems that the release amd64 is dynamically linked to glibc which alpine can't execute (out of the box). If you want to run it inside of alpine without docker you have to compile it manually. Follow the [steps](https://github.com/ngoduykhanh/wireguard-ui#build-binary-file) in the README but instead of running `go build -o wireguard-ui`, use `CGO_ENABLED=0 go build -o wireguard-ui` to build the binary.
