### ISSUE TITLE
Activating user without applying whole config

### ISSUE THREAD

**Issue by sznees** [ngoduykhanh/wireguard-ui#567]
Hello there,

my issue is following:
When I apply the config to add a new user, every other user gets disconnected and needs to reconnect. Is there any way, to add and activate an user without executing "apply config"? Like saving each user in a single file or something like that.

Would be great, if there is any way.

**Comment by beginho** [comment]
Hi @sznees,

Had same issue, I've (dirty)fixed this by modifying systemd file. As you probably know by now, there is systemd monitor (/etc/systemd/system/wgui.path) that monitors wireguard config file /etc/wireguard/wg0.conf (or whatever you use as config file) for any changes. If changes are detected (when you press Apply Config for example), systemd service wgui (/etc/systemd/system/wgui.service) is triggered. Thing is that wgui.service uses wg-quick down/up sequence, which disconnects all clients and causes WireGuard downtime (about 5–10 seconds in my case). So...
 
**Just one note, I'm using the wireguard-ui binary on ubuntu 20.04, if you're using docker I'm not sure if this will help you...** (modifying docker container maybe?!)

After googling a little bit, found [this](https://whiscardz.wordpress.com/2022/09/21/wireguard-hot-reload-config/) to be very useful, it turns out that "wg syncconf" command will apply changes without downtime, so I've: 

1. created little sh script /usr/local/bin/gw_reload.sh with following content 
    (make sure you add correct wireguard interface name, mine was wg0):
```
#!/bin/bash
echo "Wireguard UI: Reloading wireguard after config change (wg0)."
/usr/bin/wg syncconf wg0 <(/usr/bin/wg-quick strip wg0)
```
3. gave it execute rights (in terminal): 
> chmod +x /usr/local/bin/gw_reload.sh
4. commented out ExecStart= line in /etc/systemd/system/wgui.service and added new one that will execute my new little script, like this:
```
[Unit]
Description=Restart WireGuard
After=network.target

[Service]
Type=oneshot
#ExecStart=/usr/bin/systemctl restart wg-quick@wg0.service
ExecStart=/usr/local/bin/wg_reload.sh

[Install]
RequiredBy=wgui.path
```
5. After saving changes in wgui.service, i had to reload systemd configuration in terminal
> systemctl daemon-reload

6. Make some changes in WireguardUI web interface (add/delete client), press Apply Config, watch output of journalctl -f in your terminal and deal with the errors :) 

> ... systemd[1]: Starting Restart WireGuard...
> ... wg_reload.sh[7128]: Wireguard UI: Reloading wireguard after config change (wg0).
> ... systemd[1]: wgui.service: Succeeded.
> ... systemd[1]: Finished Restart WireGuard.

I hope this helps or at least points you in the right direction...

**Comment by sznees** [comment]
Hello @beginho!

Thank you a lot for the exact description of your solution. It works perfect! :)

**Comment by ruohki** [comment]
I am using a docker version and used your example to make it work for the docker version as follows:

create a new file `init.sh` with the following content:
```
#!/bin/bash

# extract wg config file path, or use default
conf="$(jq -r .config_file_path db/server/global_settings.json || echo /etc/wireguard/wg0.conf)"

# manage wireguard stop/start with the container
case $WGUI_MANAGE_START in (1|t|T|true|True|TRUE)
    wg-quick up "$conf"
    trap 'wg-quick down "$conf"' SIGTERM # catches container stop
esac

# manage wireguard restarts
case $WGUI_MANAGE_RESTART in (1|t|T|true|True|TRUE)
    [[ -f $conf ]] || touch "$conf" # inotifyd needs file to exist
    inotifyd - "$conf":w | while read -r event file; do
        interface=$(echo $file | awk -F'/' '{print $4}' | awk -F'.' '{print $1}')
        /usr/bin/wg syncconf "$interface" <(/usr/bin/wg-quick strip "$interface")
#        wg-quick down "$file"
#        wg-quick up "$file"
    done &
esac


./wg-ui &
wait $!
```

give it execute permissions
`chmod +x ./init.sh`

update your compose file to overwrite the current `init.sh`

```
volumes:
   ...
   ./init.sh:/app/init.sh
```

restart everything
`docker compose restart`

profit
