### ISSUE TITLE
[feature] Consider support for AmneziaWG

### ISSUE THREAD

**Issue by zilexa** [ngoduykhanh/wireguard-ui#574]
Please see: 
https://amnezia.org/en/learn-more/31_amneziawg and https://github.com/amnezia-vpn

> 
> [AmneziaWG](https://github.com/amnezia-vpn/amnezia-wg) is a contemporary version of the popular VPN protocol, WireGuard. It's a fork of [WireGuard-Go](https://github.com/WireGuard/wireguard-go) and offers protection against detection by Deep Packet Inspection (DPI) systems. At the same time, it retains the simplified architecture and high performance of the original.
> 
> The precursor, WireGuard, is known for its efficiency but had issues with detection due to its distinctive packet signatures.
> AmneziaWG addresses this problem by employing advanced obfuscation methods, allowing its traffic to blend seamlessly with regular internet traffic.
> As a result, AmneziaWG maintains high performance while adding an extra layer of stealth, making it a superb choice for those seeking a fast and discreet VPN connection.
> 
> Features of AmneziaWG include:
> 
>     Availability with AmneziaVPN on all platforms.
>     Low energy consumption.
>     Minimal configuration needed.
>     Undetectable by DPI analysis systems, resistant to blocking.
>     Operates over the UDP network protocol.

**Comment by zaknick** [comment]
I researched amnezia vpn and found that they were financially supported by an "accelerator" program funding russian "political opposition". 
I will refrain from dealing with the politics of this fact I just stated because Github is not the place for it, but I know for a fact that they are unsavory characters. As for them coming up with a better protocol than Jason Donnenfeld, well... I'd have to see it to believe it.

**Comment by zilexa** [comment]
Sorry, I should have done this research before posting this FR! Thanks for being sharp.

**Comment by stone-w4tch3r** [comment]
Oh guys, seems like нou're looking at this project completely from the wrong side.
Here in Russia normal internet is almost broken, and such beautiful project as amnezia is our main hope for bypassing censorship. They not only provide VPN tools that can penetrate through government's firewalls (which clean wireguard cant), but do this in open-source manner and even provide free access to basic services such as facebook/youtube.

Of course such big and impactful project is impossible without funding, and I see completely no problem that people want to fight for freedom, or at least for free access to information.

Maybe from outer perspective Amnezia may look unsavory, but this is only because you don't need such tools to bypass censorship and have not heard of them.

So, mostly I wanted to advocate for them, but also I would like to ask you to add support for their core. Currently there is no simple/beautiful solution to manage it, and integration with your panel would be a great help!

Anyway, thanks for your project
