### ISSUE TITLE
update-client  api error

### ISSUE THREAD

**Issue by betwowt** [ngoduykhanh/wireguard-ui#74]
/update-client  api error

ip xxx.xxx.xxx.xxx does not belong to any network addresses of WireGuard server

I use nat 2 nat to build wireguard,This check is good, but lacks flexibility,I hope to remove this check

**Comment by zGansalloz** [comment]
did you solve this problem?

**Comment by FewKinG** [comment]
Got a similar problem, I want to route traffic from VPN clients into one client's local network. I setup forwarding/NAT correctly and everything works when I edit the wireguard config manually and add the clients local subnet to AllowedIPs in the server config. But I cannot achieve the same configuration through the UI. I tried adding it to the AllowedIPs field in the edit client dialog, but that does only affect the client's configuration, not the server's. Adding it to the "IP Allocation" setting does give me the above described error because the entered subnet is not one that the host is directly connected through via any of its network interfaces.
