### ISSUE TITLE
Client update not working

### ISSUE THREAD

**Issue by samikroon** [ngoduykhanh/wireguard-ui#89]
I just started wireguard-ui for the first time, made some users, then I wanted to edit some of them. But the update-client call does not seem to include the correct info in its body, the id for example is set to an empty string, email is also an empty string while it was already filled.

Body of the update-client call:

```
{
    "id":"",
    "name":"<filled out correctly but contains private info>",
    "email":"",
    "allocated_ips":["172.16.2.2/32"],
    "allowed_ips":["172.16.0.0/12"],
    "use_server_dns":false,
    "enabled":true
}
```

**Comment by gerwim** [comment]
It seems this only happens if you edit an user right after adding. Hitting refresh first works. This is certainly a bug though ;-).

**Comment by jan-di** [comment]
I cannot second that - for me, updating never works. I have found the issue: 

The page contains two elements with the id `_client_id`. When the edit client form is submitted, the client-id value is fetched from the wrong element (the id element inside the edit email form), thats why the POST request does not contain a client id.

**Comment by N4v41** [comment]
i'm not familiar with github and development but i forked and corrected this error is just like @jan-di said is duplicated html ids,
https://github.com/N4v41/wireguard-ui here  you can find the corrected clients.html  and i had built the images for docker with support multiarch, because i use it in raspberry pi, available here https://hub.docker.com/r/n4v41/wireguard-ui
I will try to make a pull request later
