### ISSUE TITLE
after update to v0.3.2 not showing clients

### ISSUE THREAD

**Issue by karkaaa** [ngoduykhanh/wireguard-ui#95]
hello,

i am using binary file and after update from 0.3.0 to 0.3.2 not showing clients

but i can login with old users config

thank you

**Comment by paklids** [comment]
The wireguard-ui system keeps the its own database (a collection of json files really) inside a directory called `db`. You'll need to see if these were moved or erased somehow. It is possible to backup & restore these files (I use rsync for that). I'd recommend not clicking `appy` in the UI while it shows no users because it could overwrite what is running in wireguard. BTW - I'm using this via docker & not using the golang binary so YMMV.

**Comment by karkaaa** [comment]
listed db dir:
![image](https://user-images.githubusercontent.com/34538939/132329941-8f3a2018-9f99-40fd-8220-585685a92db9.png)

old user inside but in wireguard-ui not showing

**Comment by karkaaa** [comment]
restored from backup
